apiVersion: v1
kind: Namespace
metadata:
  name: test

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-server
  namespace: test
  labels:
    app: simple-http-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-server
  template:
    metadata:
      labels:
        app: simple-http-server
    spec:
      containers:
        - name: simple-http-server
          image: simple-http-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: simple-http-server-service
  namespace: test
spec:
  selector:
    app: simple-http-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-http-client
  namespace: test
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simple-http-client
            image: simple-http-client:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure